#define MAIN              257
#define LEFT_KEY          258
#define RIGHT_KEY         259
#define LEFT_BRACKET      260
#define RIGHT_BRACKET     261
#define SEMICOLON         262
#define LEFT_PARENTHESIS  263
#define RIGHT_PARENTHESIS 264
#define COMA              265
#define ASSIGN            266
#define IF                267
#define THEN              268
#define ELSE              269
#define WHILE             270
#define RETURN            271
#define FOR               272
#define ASSIGN_FOR        300
#define TO                273
#define DO                274
#define OUT               275
#define IN                276
#define INITVAR           277
#define ENDVAR            278
#define PLUSPLUS          279
#define AT                280
#define DOLLAR            281
#define NEG               282
#define COUNT             302
#define QUEST             303
#define SYMBOL_OP         283
#define RELATION_OP       296
#define EQUALS_OP         299
#define AND_OP            295
#define OR_OP             297
#define XOR_OP            298
#define MINUSMINUS        284
#define BINARY_OP         285
#define BINARY_LIST_OP_I  301
#define BINARY_LIST_OP_L  302
#define LIST_OP           286
#define LIST_OF           287
#define BASIC_TYPES       288
#define CONST_INT         289
#define CONST_DOUBLE      290
#define CONST_BOOLEAN     291
#define CONST_CHAR        292
#define CADENA            293
#define ID                294
